import { createHash, randomUUID } from "node:crypto";
import { createConnection } from "node:net";
import { encodeEngineBrokerFrame,EngineBrokerFrameDecoder,parseEngineBrokerResponse } from "./engineBrokerProtocol.js";

export interface EngineBrokerTurnClient { turn(agentId:string,wakeId:string,prompt:string,mcpEndpoint:string,signal?:AbortSignal):Promise<string>; }
export class EngineBrokerControlClient implements EngineBrokerTurnClient {
  constructor(private readonly socketPath="/run/daimon-engine-broker/control.sock"){}
  async ready():Promise<void>{const requestId=randomUUID(),socket=createConnection({path:this.socketPath}),decoder=new EngineBrokerFrameDecoder();await new Promise<void>((resolve,reject)=>{let settled=false;const fail=()=>{if(settled)return;settled=true;socket.destroy();reject(new Error("engine broker unavailable"));};socket.once("error",fail);socket.once("close",fail);socket.once("connect",()=>socket.write(encodeEngineBrokerFrame({version:"noopolis.daimon.engine-broker.v1",kind:"health",requestId})));socket.on("data",(chunk)=>{try{for(const value of decoder.push(chunk)){const response=parseEngineBrokerResponse(value);if(response.kind!=="ready"||response.requestId!==requestId||settled)throw new Error();settled=true;socket.destroy();resolve();}}catch{fail();}});});}
  async turn(agentId:string,wakeId:string,prompt:string,mcpEndpoint:string,signal?:AbortSignal):Promise<string>{
    const turnId=createHash("sha256").update(`${agentId}\0${wakeId}`).digest("hex"),requestId=randomUUID();const request={version:"noopolis.daimon.engine-broker.v1",kind:"start_turn",requestId,turnId,agentId,wakeId,prompt,mcpEndpoint} as const;const socket=createConnection({path:this.socketPath});const decoder=new EngineBrokerFrameDecoder();
    return new Promise<string>((resolve,reject)=>{let accepted=false,settled=false;const fail=()=>{if(settled)return;settled=true;cleanup();reject(new Error("engine broker unavailable"));};const cleanup=()=>{signal?.removeEventListener("abort",abort);socket.destroy();};const abort=()=>fail();signal?.addEventListener("abort",abort,{once:true});if(signal?.aborted)return abort();socket.once("connect",()=>socket.write(encodeEngineBrokerFrame(request)));socket.on("data",(chunk)=>{try{for(const value of decoder.push(chunk)){const response=parseEngineBrokerResponse(value);if(response.kind==="ready"||response.requestId!==requestId||response.turnId!==turnId)throw new Error();if(response.kind==="accepted"){if(accepted)throw new Error();accepted=true;continue;}if(!accepted||settled)throw new Error();settled=true;cleanup();if(response.kind==="completed")resolve(response.text);else reject(new Error(response.diagnostic ? `engine broker turn failed (${response.diagnostic.stage}/${response.diagnostic.failureClass}; exit=${response.diagnostic.exitCode}; signal=${response.diagnostic.termSignal})` : "engine broker turn failed"));}}catch{fail();}});socket.once("error",fail);socket.once("close",()=>{if(!settled)fail();});});
  }
}
