import { chmod, lstat, unlink } from "node:fs/promises";
import { createServer, type Server, type Socket } from "node:net";
import { encodeEngineBrokerFrame,EngineBrokerFrameDecoder,parseEngineBrokerRequest,type EngineBrokerResponse } from "./engineBrokerProtocol.js";
import { EngineBrokerTurnFailure } from "./grokEngineBroker.js";
export interface EngineBrokerServiceEngine {
  turn(agentId:string,wakeId:string,prompt:string,mcpEndpoint:string,signal?:AbortSignal):Promise<Readonly<{text:string;workerPid:number;workerUid:number;workerStartTime:string}>>;
  readiness():Readonly<{providerProxyPort:number;mcpFacadePort:number;registrations:number;credentialStale:boolean;realmLease:boolean;workerIsolation:boolean}>;
  close():Promise<void>;
}

export function startEngineBrokerService(broker:EngineBrokerServiceEngine,socketPath="/run/daimon-engine-broker/backend.sock"){
  return startEngineBrokerServiceWithIdentity(broker,socketPath,2100);
}
export async function startEngineBrokerServiceWithIdentity(broker:EngineBrokerServiceEngine,socketPath:string,expectedUid:number){
  if(process.getuid?.()!==expectedUid)throw new Error("engine broker service requires broker identity");await removeOwnedSocket(socketPath,expectedUid);const active=new Map<string,AbortController>(),connections=new Set<Socket>();
  const server=createServer((socket)=>{connections.add(socket);socket.once("close",()=>connections.delete(socket));handle(socket,broker,active);});await listen(server,socketPath);
  try{await chmod(socketPath,0o600);await verifySocket(socketPath,expectedUid);}catch(error){await closeServer(server,connections);await unlink(socketPath).catch(()=>undefined);throw error;}
  let closed=false;return {close:async()=>{if(closed)return;closed=true;for(const controller of active.values())controller.abort();const results=await Promise.allSettled([closeServer(server,connections),broker.close()]);await unlink(socketPath).catch(()=>undefined);const failures=results.flatMap((result)=>result.status==="rejected"?[result.reason]:[]);if(failures.length)throw new AggregateError(failures,"engine broker service shutdown failed");},health:()=>({activeTurns:active.size,socketPath})};
}
function handle(socket:Socket,broker:EngineBrokerServiceEngine,active:Map<string,AbortController>):void{const decoder=new EngineBrokerFrameDecoder();let started=false,owned:Readonly<{turnId:string;controller:AbortController}>|undefined;socket.once("close",()=>owned?.controller.abort());socket.on("data",(chunk)=>{try{for(const value of decoder.push(chunk)){const request=parseEngineBrokerRequest(value);if(request.kind==="health"){if(started)throw new Error();started=true;const ready=broker.readiness();if(ready.providerProxyPort!==43123||ready.mcpFacadePort!==43124||ready.registrations<1||ready.credentialStale||!ready.realmLease||!ready.workerIsolation)throw new Error();return send(socket,{version:request.version,kind:"ready",requestId:request.requestId,brokerUid:2100,providerProxyPort:43123,mcpFacadePort:43124,registrations:ready.registrations,credentialStale:false,realmLease:true,workerIsolation:true});}if(request.kind==="cancel_turn"){active.get(request.turnId)?.abort();continue;}if(started||active.has(request.turnId))throw new Error();started=true;const controller=new AbortController();owned={turnId:request.turnId,controller};active.set(request.turnId,controller);socket.write(encodeEngineBrokerFrame({version:request.version,kind:"accepted",requestId:request.requestId,turnId:request.turnId}));void broker.turn(request.agentId,request.wakeId,request.prompt,request.mcpEndpoint,controller.signal).then((result)=>send(socket,{version:request.version,kind:"completed",requestId:request.requestId,turnId:request.turnId,...result}),(error:unknown)=>send(socket,{version:request.version,kind:"failed",requestId:request.requestId,turnId:request.turnId,code:error instanceof EngineBrokerTurnFailure?error.code:controller.signal.aborted?"cancelled":"engine_failed",...(error instanceof EngineBrokerTurnFailure&&error.diagnostic?{diagnostic:error.diagnostic}:{})})).finally(()=>{if(active.get(request.turnId)===controller)active.delete(request.turnId);owned=undefined;});}}catch{socket.destroy();}});}
function send(socket:Socket,response:EngineBrokerResponse):void{if(!socket.destroyed)socket.end(encodeEngineBrokerFrame(response));}
async function removeOwnedSocket(file:string,uid:number):Promise<void>{try{const entry=await lstat(file);if(!entry.isSocket()||Number(entry.uid)!==uid)throw new Error("unsafe broker socket");await unlink(file);}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}}
async function verifySocket(file:string,uid:number):Promise<void>{const entry=await lstat(file);if(!entry.isSocket()||Number(entry.uid)!==uid||(Number(entry.mode)&0o777)!==0o600)throw new Error("unsafe broker socket");}
function listen(server:Server,file:string):Promise<void>{return new Promise((resolve,reject)=>{server.once("error",reject);server.listen(file,()=>{server.off("error",reject);resolve();});});}
function closeServer(server:Server,connections:Set<Socket>):Promise<void>{for(const socket of connections)socket.destroy();return new Promise((resolve,reject)=>server.close((error)=>error?reject(error):resolve()));}
