import { createHash } from "node:crypto";
import { constants } from "node:fs";
import { lstat,open } from "node:fs/promises";

type Snapshot=Readonly<{dev:number;ino:number;size:number;mtimeMs:number;denyPaths:readonly string[]}>;
export class GrokWorkerAttestationFailure extends Error { constructor(readonly failureClass:"profile_missing"|"profile_invalid"){super("Grok worker isolation attestation unavailable");} }
export async function prepareGrokWorkerAttestation(input:Readonly<{profilePath:string;eventsPath:string;profileSha256:string;workerUid:number;brokerGid:number}>):Promise<Snapshot>{
  const profile=await secureOpen(input.profilePath,0,0,0o444,65_536);let bytes:Buffer|undefined;let denyPaths:readonly string[]=[];try{bytes=await profile.readFile();if(createHash("sha256").update(bytes).digest("hex")!==input.profileSha256)throw new Error();const line=bytes.toString("utf8").split("\n").find((entry)=>entry.startsWith("deny = "));const parsed=JSON.parse(line?.slice(7)??"null") as unknown;if(!Array.isArray(parsed)||parsed.length<3||parsed.some((entry)=>typeof entry!=="string")||new Set(parsed).size!==parsed.length)throw new Error();denyPaths=[...parsed].sort();}catch{throw new Error("Grok worker isolation attestation unavailable");}finally{bytes?.fill(0);await profile.close();}
  const events=await secureOpen(input.eventsPath,input.workerUid,input.brokerGid,0o640,16*1024*1024);try{const stat=await events.stat();return{dev:Number(stat.dev),ino:Number(stat.ino),size:Number(stat.size),mtimeMs:Number(stat.mtimeMs),denyPaths};}finally{await events.close();}
}
export async function verifyGrokWorkerAttestation(input:Readonly<{eventsPath:string;workerUid:number;brokerGid:number;workspace:string}>,before:Snapshot):Promise<void>{
  let handle:Awaited<ReturnType<typeof secureOpen>>;try{handle=await secureOpen(input.eventsPath,input.workerUid,input.brokerGid,0o640,16*1024*1024);}catch{throw new GrokWorkerAttestationFailure("profile_invalid");}let bytes:Buffer|undefined;try{const stat=await handle.stat();if(Number(stat.dev)!==before.dev||Number(stat.ino)!==before.ino)throw new GrokWorkerAttestationFailure("profile_invalid");if(Number(stat.size)<=before.size)throw new GrokWorkerAttestationFailure("profile_missing");bytes=Buffer.alloc(Number(stat.size)-before.size);const read=await handle.read(bytes,0,bytes.length,before.size);if(read.bytesRead!==bytes.length)throw new GrokWorkerAttestationFailure("profile_invalid");const after=await handle.stat();if(Number(after.size)!==Number(stat.size)||Number(after.mtimeMs)!==Number(stat.mtimeMs))throw new GrokWorkerAttestationFailure("profile_invalid");parseGrokWorkerProfileApplied(bytes,input.workspace,before.denyPaths);}catch(error){if(error instanceof GrokWorkerAttestationFailure)throw error;throw new GrokWorkerAttestationFailure("profile_invalid");}finally{bytes?.fill(0);await handle.close();}
}
export function parseGrokWorkerProfileApplied(bytes:Uint8Array,workspace:string,denyPaths:readonly string[]=[]):void{try{const lines=Buffer.from(bytes).toString("utf8").trim().split("\n");const event=JSON.parse(lines.at(-1)??"null") as Record<string,unknown>|null;const observed=Array.isArray(event?.deny_paths)?event.deny_paths.filter((entry):entry is string=>typeof entry==="string").sort():[];if(event?.event_type!=="ProfileApplied"||event.profile!=="daimon-strict"||event.enforced!==true||event.restrict_network!==true||event.platform!=="linux/landlock"||event.workspace!==workspace||JSON.stringify(observed)!==JSON.stringify([...denyPaths].sort()))throw new Error();}catch{throw new Error("Grok worker isolation attestation unavailable");}}
async function secureOpen(file:string,uid:number,gid:number,mode:number,max:number,links=1){try{const before=await lstat(file);const handle=await open(file,constants.O_RDONLY|constants.O_NOFOLLOW);const stat=await handle.stat();if(!stat.isFile()||stat.isSymbolicLink()||Number(stat.uid)!==uid||Number(stat.gid)!==gid||(Number(stat.mode)&0o777)!==mode||Number(stat.nlink)!==links||Number(stat.size)>max||before.dev!==stat.dev||before.ino!==stat.ino){await handle.close();throw new Error();}return handle;}catch{throw new Error("Grok worker isolation attestation unavailable");}}
